name: Simple CI/CD Pipeline

# When to run this workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# What to do
jobs:
  # Job 1: Test our code
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Get our code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'  # This caches npm dependencies for faster builds
        
    - name: Install dependencies
      run: npm ci  # Use npm ci instead of npm install for faster, reliable builds
      
    - name: Run tests
      run: npm test

  # Job 2: Deploy (only when pushing to main)
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST "https://api.render.com/deploy/srv-d17c583e5dus73doie1g?key=${{ secrets.RENDER_HOOK }}"
      env:
        # Optional: Add timeout to prevent hanging
        CURL_TIMEOUT: 30